$(document).ready(function(){
	$('#RoG_Strix_GL12').load("html/Products/RoG_Strix_GL12.html");
	$('#ABS_Mage_M').load("html/Products/ABS_Mage_M.html");
	$('#MSI_Trident_XPlus').load("html/Products/MSI_Trident_XPlus.html");
	$('#ASUS_VG245H').load("html/Products/ASUS_VG245H.html");
	$('#ACER_Z1_Z321QU').load("html/Products/ACER_Z1_Z321QU.html");
	$('#ASUS_XG32VQ').load("html/Products/ASUS_XG32VQ.html");
	$('#Roswell_Fusion_C40').load("html/Products/Roswell_Fusion_C40.html");
	$('#CM_Devastator_3').load("html/Products/CM_Devastator_3.html");
	$('#CM_Storm_Devastator').load("html/Products/CM_Storm_Devastator.html");
});