$(document).ready(function(){
	$('#MSI_9SF-240').load("html/Products/MSI_9SF-240.html");
	$('#ASUS_ROG_Zephyrus_S').load("html/Products/ASUS_ROG_Zephyrus_S.html");
	$('#Acer_PH315-52-71RT').load("html/Products/Acer_PH315-52-71RT.html");
	$('#Microsoft_Surface_JKX-00001').load("html/Products/Microsoft_Surface_JKX-00001.html");
	$('#MacBook_Air_MJVE2LLA').load("html/Products/MacBook_Air_MJVE2LLA.html");
	$('#Lenovo_ThinkPad_20L7002HUS').load("html/Products/Lenovo_ThinkPad_20L7002HUS.html");
	$('#Microsoft_Surface_Pro_4').load("html/Products/Microsoft_Surface_Pro_4.html");
	$('#Apple_iPad_Air').load("html/Products/Apple_iPad_Air.html");
	$('#Lenovo_yoga_tab_3').load("html/Products/Lenovo_yoga_tab_3.html");
});